version: "3.9"
services:
    web:     
       # image: "sshrav/apidotnet"
        build: .
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "My_Password"
            ACCEPT_EULA: "Y"
        volumes:
            - testmssql:/var/opt/mssql

volumes:
  testmssql:
 