# Create the SQL Server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      hostname: sqlserver      
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:              
      - name: mssql
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        env:
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: MSSQL_PID
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ACCEPT_EULA
        - name: MSSQL_AGENT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: MSSQL_AGENT_ENABLED  
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD               
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql   
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data