apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "proxy"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"  
    spec:
      containers:
      - name: proxy
        image: sshrav/workshop2:1.6
        ports:
        - containerPort: 80
        - containerPort: 443