apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "415585899039-pbpsalf2ndpmpnd0gm6ooithoj7gn318.apps.googleusercontent.com"
  - name: clientSecret
    value: "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"
  - name: scopes
    value: "https://www.googleapis.com/auth/userinfo.email"
  - name: authURL
    value: "https://accounts.google.com/o/oauth2/v2/auth"
  - name: tokenURL
    value: "https://accounts.google.com/o/oauth2/token"
  - name: redirectURL
    value: "http://dummy.com/v1.0/invoke/echoapp/method/echo"
  - name: authHeaderName
    value: "authorization"   
  - name: forceHTTPS
    value: "false"           